import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Login() {
    return(
        <div className={styles.container}>
            <Head>
            <title>ログイン</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>

                <p>
                <input type="text" name="email" size="30" placeholder="メールアドレス"/>
                </p>
                <p>
                <input type="text" name="password" size="30" placeholder="パスワード"/>
                </p>
                <p>
                <Link href="/mypage">
                <button class="button">ログイン</button>
                </Link>
                </p>
                
            </main>
        </div>
    );
}