import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';



export default function Mypage() {

    return(
        <div className={styles.container}>
            <Head>
            <title>マイページ</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>

                <p>
                <Link href="/search">
                <button class="button">旅程を探す</button>
                </Link>
                </p>
                

            </main>
        </div>
    );
}