import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Register() {
    return(
        <div className={styles.container}>
            <Head>
            <title>会員登録</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>

                <form>
                <div class="register">
                    <input type="text" name="first_name" id="first_name" placeholder="例）鈴木"/>
                    <input type="text" name="last_name" id="last_name" placeholder="例）太郎"/>
                </div>
                <div class="register">
                    <input class="inputs" type="email" name="email" id="email" placeholder="○○○.jp"/>
                </div>
                <p>
                <button class="button">送信</button>
                </p>
                </form>

            </main>
        </div>
    );
}